version: '3'
services:
  api:
    container_name: main_api
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - app-network
    depends_on:
      - log-sender
      - redis
    

  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq
    container_name: logs-rabbitmq-container
    environment:
      ports: "-5672:15672"
    ports: 
       - "5672:5672"
       - "15672:15672"
    networks:
      - app-network

  log-sender:
    image: log-sender
    container_name: log-sender
    entrypoint: python main.py
    networks:
      - app-network
    depends_on:
      - rabbitmq
      
networks:
  app-network:
    driver: bridge